version_num: 1
min_minutes: 30
ethnicity_extract: false

required_signals:
  ecg_labels: ['II']
  ppg_labels: ['Pleth']
  abp_labels: ['abp', 'art']
  custom_label: 0

mimic_variants:
  "3":
    mimic_path: 'mimic3wdb-matched/1.0/'
    max_subjects: 20 # Max Available 10999
    annotation_csv: 'mimic3_annotations.csv'
  "4":
    mimic_path: 'mimic4wdb/0.1.0/'
    max_subjects: 20 # 198
    annotation_csv: null

